---
- name: Check Cluster Exists
  ansible.builtin.command :
    argv:
      - kind
      - get
      - clusters
  register: check_cluster

- name: Delete Existing Cluster
  ansible.builtin.command :
    argv:
      - kind
      - delete
      - cluster
      - --name=clusterapi
  when: check_cluster.stdout.find('clusterapi') != -1
  tags: [ 'never', 'clean' ]

- name: Clean LB Proxy port 443
  community.general.docker_container:
    name: kind-proxy-443
    state: absent
  tags: [ 'never', 'clean' ]

- name: Clean LB Proxy port 80
  community.general.docker_container:
    name: kind-proxy-80
    state: absent
  tags: [ 'never', 'clean' ]