- name: Create a k8s namespace
  k8s:
    name: ca-system
    api_version: v1
    kind: Namespace
    state: present

- name: Install Consul
  helm_cli:
    chart_ref: hashicorp/consul
    binary_path: helm
    state: present
    namespace: ca-system
    name: consul
    values:
      global:
        name: consul
        datacenter: kind-local-dev
        enablePodSecurityPolicies: true
      client:
        enabled: false
      dns:
        clusterIP: 10.96.96.96
      server:
        storage: 1Gi
      syncCatalog:
        enabled: true
        default: false
        addK8SNamespaceSuffix: false

- name: Patch the Catalog to look at the internal service for testing
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Deployment
      metadata:
        name: consul-sync-catalog
        namespace: ca-system
      spec:
        template:
          spec:
            containers:
            - name: consul-sync-catalog
              env:
                - name: CONSUL_HTTP_ADDR
                  value: http://consul-server:8500

- name: Create a Service object from an inline definition
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: coredns
        namespace: kube-system
      data:
        Corefile: |
          .:53 {
              errors
              health {
                lameduck 5s
              }
              ready
              kubernetes cluster.local in-addr.arpa ip6.arpa {
                pods insecure
                fallthrough in-addr.arpa ip6.arpa
                ttl 30
              }
              prometheus :9153
              forward . /etc/resolv.conf
              cache 30
              loop
              reload
              loadbalance
          }
          service.consul:53 {
              errors
              forward . 10.96.96.96
          }
          kind-local-dev.consul:53 {
              errors
              cache 30
              forward . 10.96.96.96
          }
          consul:53 {
              errors
              cache 30
              forward . 10.34.1.250 10.34.21.250 10.34.41.250 {
                except kind-local-dev.consul
              }
          }

