---
- name: Check Cluster Exists
  command:
    argv:
      - kind
      - get
      - clusters
  register: check_cluster

- name: Delete Existing Cluster
  command:
    argv:
      - kind
      - delete
      - cluster
  when: check_cluster.stdout.find('kind') != -1
  register: delete_cluster

- name: Start Kind Cluster
  command:
    argv:
      - kind
      - create
      - cluster
      - --config=kind-config.yaml
      - --image=kindest/node:v1.14.9@sha256:00fb7d424076ed07c157eedaa3dd36bc478384c6d7635c5755746f151359320f
  args:
    chdir: "{{role_path}}/files"

