---
- name: Check Cluster Exists
  ansible.builtin.command :
    argv:
      - kind
      - get
      - clusters
  register: check_cluster

- name: Delete Existing Cluster
  ansible.builtin.command :
    argv:
      - kind
      - delete
      - cluster
      - --name=clusterapi
  when: check_cluster.stdout.find('clusterapi') != -1
  register: delete_cluster

- name: Start Kind Cluster
  ansible.builtin.command :
    argv:
      - kind
      - create
      - cluster
      - --config=kind-config.yaml
      - --name=clusterapi
  args:
    chdir: "{{role_path}}/files"

