---
- name: Create a k8s namespace
  k8s:
    name: ca-system
    api_version: v1
    kind: Namespace
    state: present

- name: Wait for kube-system to be ready
  k8s_info:
    kind: Pod
    namespace: kube-system
  register: pods_output
  retries: 20
  delay: 45
  until: "pods_output | json_query('resources[*].status.containerStatuses[?ready == `false`][].ready | contains(@, `false`)') != true"

- name: Install KubeDB Operator
  helm_cli:
    chart_repo_url: https://charts.appscode.com/stable
    chart_ref: kubedb
    binary_path: helm
    chart_version: 0.12.0
    state: present
    name: kubedb
    namespace: ca-system
    values:
      enableAnalytics: false

- name: Every update triggers a new tls for kubedb
  command:
    argv:
      - kubectl
      - delete
      - pods
      - -n=ca-system
      - -l app=kubedb

- name: Wait for kubedb to be ready
  k8s_info:
    kind: Pod
    namespace: ca-system
  register: pods_output
  retries: 8
  delay: 10
  until: "pods_output | json_query('resources[*].status.containerStatuses[?ready == `false`][].ready | contains(@, `false`)') != true"

- name: Install KubeDB Catalog
  helm_cli:
    chart_repo_url: https://charts.appscode.com/stable
    chart_ref: kubedb-catalog
    binary_path: helm
    chart_version: 0.12.0
    state: present
    namespace: ca-system
    name: kubedb-catalog
  until: "pods_output | json_query('resources[*].status.containerStatuses[?ready == `false`][].ready | contains(@, `false`)') != true"

