---
- name: configure kind
  include: kind.yml
  tags:
    - build
    - minimum

- name: configure network
  include: network.yml
  tags:
    - update
    - minimum
    - network

- name: configure loadbalancer
  include: metallb.yml
  tags:
    - update
    - minimum
    - loadbalancer

- name: configure monitoring
  include: monitoring.yml
  tags:
    - update
    - monitoring

- name: Install Traefik
  include: traefik.yml
  tags:
    - update
    - traefik
