---
- name: clean cluster
  include: clean.yml
  tags:
    - never
    - clean

- name: configure kind
  include: kind.yml
  tags:
    - minimum
    - network

- name: configure network
  include: network.yml
  tags:
    - network

- name: configure loadbalancer
  include: metallb.yml
  tags:
    - add-features
    - loadbalancer

- name: configure monitoring
  include: monitoring.yml
  tags:
    - add-features
    - monitoring

- name: Install Traefik
  include: traefik.yml
  tags:
    - add-features
    - traefik
