---
- name: clean cluster
  include: clean.yml
  tags:
    - never
    - clean

- name: configure kind
  include: kind.yml

- name: configure network
  include: network.yml

- name: configure loadbalancer
  include: metallb.yml
  when: metallb_enabled == True

- name: Install Ingress
  include: ingress.yml
  when: metallb_enabled == True and ingress_enabled == True

- name: configure monitoring
  include: monitoring.yml
  when: monitoring_enabled == True
