---
- name: configure kind
  include: kind.yml
  tags:
    - build

- name: configure network
  include: network.yml
  tags:
    - update
    - network

- name: configure consul
  include: consul.yml
  tags:
    - update
    - consul

- name: configure monitoring
  include: monitoring.yml
  tags:
    - update
    - monitoring

- name: configure loadbalancer
  include: metallb.yml
  tags:
    - update
    - loadbalancer

- name: Install Traefik
  include: traefik.yml
  tags:
    - update
    - traefik
