---
- name: configure kind
  include: kind.yml

- name: configure network
  include: network.yml

- name: configure consul
  include: consul.yml

- name: configure kubedb
  include: kubedb.yml

- name: configure monitoring
  include: monitoring.yml