---
- name: Download Metallb Namespace
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/namespace.yaml
    dest: /tmp/metallb-namespace.yml

- name: Create metallb namespace
  community.kubernetes.k8s:
    name: metallb-system
    state: present
    src: /tmp/metallb-namespace.yml

- name: Download Metallb
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/metallb.yaml
    dest: /tmp/metallb.yml

- name: Create metallb
  community.kubernetes.k8s:
    name: metallb-system
    state: present
    src: /tmp/metallb.yml

- name: Create a dodgy secret for metallb
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: memberlist
        namespace: metallb-system
      data:
        secretkey: dGhpc2lzbm90c2VjcmV0cmVhbGx5

- name: Create metallb Config
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: config
        namespace: metallb-system
      data:
        config: |
          address-pools:
          - name: default
            protocol: layer2
            addresses:
            - 172.18.255.1-172.18.255.250