- name: Wait for kube-system to be ready
  community.kubernetes.k8s_info:
    kind: Pod
    namespace: kube-system
  register: pods_output
  retries: 20
  delay: 45
  until: "pods_output | json_query('resources[*].status.containerStatuses[?ready == `false`][].ready | contains(@, `false`)') != true"

- name: Get Helm repository
  community.kubernetes.helm_repository:
    name: prometheus-community
    repo_url: "https://prometheus-community.github.io/helm-charts"

- name: Install Prometheus Operator
  community.kubernetes.helm:
    name: ca-prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: monitoring
    chart_version: 13.13.1
    create_namespace: yes
    update_repo_cache: yes
    values:
      nodeExporter:
        relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
          - __meta_kubernetes_pod_node_name
          targetLabel: kubernetes_node
      kubelet:
        metricRelabelings:
        - action: replace
          sourceLabels:
          - node
          targetLabel: instance
  until: "pods_output | json_query('resources[*].status.containerStatuses[?ready == `false`][].ready | contains(@, `false`)') != true"
