- name: Add Traefik repository
  community.kubernetes.helm_repository:
    name: traefik
    repo_url: https://helm.traefik.io/traefik

- name: Create a k8s namespace
  community.kubernetes.k8s:
    name: ingress
    api_version: v1
    kind: Namespace
    state: present

- name: Install Traefik
  community.kubernetes.helm:
    name: traefik
    chart_ref: traefik/traefik
    release_namespace: ingress
    update_repo_cache: yes
